 const NETWORK_ERR = "0050";

 const WX_GETOPENID_ERR ='0051';
 const WX_GETUSERINFO_ERR ='0052';
 const WX_REFRESHOPENID_ERR ='0053';

module.exports = {
    NETWORK_ERR,
    WX_GETOPENID_ERR,
    WX_GETUSERINFO_ERR,
    WX_REFRESHOPENID_ERR
}